server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_boot?characterEncoding=UTF8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mybatis/sqlmap/*.xml
  type-aliases-package: com.boot.model

pagehelper:
  helperDialect: mysql

logging:
  config: classpath:logback-spring.xml